### ISSUE TITLE
No f-strings in Python 3.5

### ISSUE THREAD

**Issue by dpeschman** [smoofra/mslex#1]
* mslex version: 0.3
* Python version: 3.5.6
* Operating System: CentOS 7

Syntax error mslex.py line 83 on import.  f-strings were introduced in Python 3.6.

```
$ python3.5 -m venv zzz
$ . zzz/bin/activate
(zzz) $ pip install mslex
...
Successfully installed mslex-0.3.0
(zzz) $ python
Python 3.5.6 (default, Nov 16 2018, 15:51:11)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mslex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zzz/lib64/python3.5/site-packages/mslex.py", line 83
    raise ValueError(f"unquoted cmd metacharacters in string: {repr(s)}")
                                                                       ^
SyntaxError: invalid syntax
>>>
```

**Comment by smoofra** [comment]
fixed
