### ISSUE TITLE
Incorrect expressions are processed incorrectly

### ISSUE THREAD

**Issue by pomponchik** [smoofra/mslex#11]
* mslex version: 1.2.0
* Python version: 3.12.4
* Operating System: macOS

### Description

Hello!

When i pass a wrong command `python -c "` to the `split()` function of your library i have not any exceptions.

A similar experiment with `shlex` raises an error:

```python
>>> from shlex import split
>>>
>>> split('python -c "')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py", line 313, in split
    return list(lex)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

I also noticed that there are no tests in the project that would check situations when the functions of your package raise exceptions.

### What I Did

```python
>>> from mslex import split
>>>
>>> split('python -c "')
['python', '-c', '']
```

**Comment by smoofra** [comment]
Amazingly, this behavior is actually correct.

``` 
C:\Users\larry>python -c "import sys; print(repr(sys.argv))" foo bar "
['-c', 'foo', 'bar', '']
```
