### ISSUE TITLE
"Unquoted CMD metacharacters" error when all right

### ISSUE THREAD

**Issue by pomponchik** [smoofra/mslex#12]
* mslex version: 1.2.0
* Python version: 3.12.4
* Operating System: macOS

### Description

I found that the `python -c "print('hello,world!')"` string is recognized by `mslex` as bad. However, I suspect that this should not be the case.

### What I Did

```python
>>> import mslex
>>>
>>> mslex.split('python -c "print(\'hello,world!\')"')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pomponchik/Desktop/Projects/suby/venv/lib/python3.12/site-packages/mslex/__init__.py", line 104, in split
    s = "".join(i())
        ^^^^^^^^^^^^
  File "/Users/pomponchik/Desktop/Projects/suby/venv/lib/python3.12/site-packages/mslex/__init__.py", line 102, in i
    raise MSLexError("Unquoted CMD metacharacters in string: " + repr(s))
mslex.exceptions.MSLexError: Unquoted CMD metacharacters in string: 'python -c "print(\'hello,world!\')"'
>>>
>>> mslex.split("python -c \"print('hello,world!')\"")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pomponchik/Desktop/Projects/suby/venv/lib/python3.12/site-packages/mslex/__init__.py", line 104, in split
    s = "".join(i())
        ^^^^^^^^^^^^
  File "/Users/pomponchik/Desktop/Projects/suby/venv/lib/python3.12/site-packages/mslex/__init__.py", line 102, in i
    raise MSLexError("Unquoted CMD metacharacters in string: " + repr(s))
mslex.exceptions.MSLexError: Unquoted CMD metacharacters in string: 'python -c "print(\'hello,world!\')"'
```

**Comment by smoofra** [comment]
`!` is a metacharacter under [certain circumstances.](https://ss64.com/nt/delayedexpansion.html)

If you don't want it to check for metacharacters, pass `check=False` to `mslex.split`

**Comment by smoofra** [comment]
er, but it is quoted, i think you're right

**Comment by smoofra** [comment]
ah, no, cmd will do variable expansion inside quotes.   This behavior is correct!

see:


```
Z:\src\mslex>type foo.bat
@echo off
SETLOCAL EnableDelayedExpansion
echo "!PATH!"

Z:\src\mslex>foo.bat
"C:\Program Files\Parallels\Parallels Tools\Applications;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\larry\AppData\Local\Microsoft\WindowsApps;"
```

**Comment by smoofra** [comment]
a safe way to quote that string would be `print^('hello,world^!'^)`
